# 메인 파일 이름을 지정하세요.
main_file = 'main.py' # fill here

# 데이타 파일들을 지정하세요.
data_files = [
    # fill here
    'Jalnan.ttf'
]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [
    # fill here
    'BackGround', 'GameMode', 'Object', 'Skill','Sound','UI'
]

